### ISSUE TITLE
New Region (Hisui region/Legends Arceus)

### ISSUE THREAD

**Issue by Charlie-X-Bear** [projeffboy/my-pokemon-team#52]
Hello!

This isn't an issue, but a request! So, I love messing around with the "Pokémon Team" Maker and was wondering if you could possibly add the Pokémon from the Hisui region, including the new final evolutions for the starters and the new evolutions and regional Pokémon (Ex. Hisuian Growlithe). Another thing I think we might like would be if you could possibly add the Pokémon from the new game Scarlett and Violett when it comes out, and yes, I know you must be very busy, but this is just a request I'd love to see!

Thank you,
Charlie

**Comment by projeffboy** [comment]
Added a while ago, forgot to close this issue
